In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

[]


In [4]:
"""

Maze structure 1
                                   ___
 _________________________________|+++|
|       |          |          |       |
|   0*  |    1          2     |   3   |
|       |          |          |       |
|__   __|____   ___|___   ____|__   __|
|       |          |          |       |
|   4   |     5    |    6     |   7   |
|                                     |
|_______|__________|__________|_______|

R = np.matrix([[-1, -1, -1, -1, 0, -1, -1, -1],
               [-1, -1, 0, -1, -1, 0, -1, -1],
               [-1, 0, -1, -1, -1, -1, 0, -1],
               [-1, -1, -1, 100, -1, -1, -1, 0],
               [0, -1, -1, -1, -1, 0, -1, -1],
               [-1, 0, -1, -1, 0, -1, 0, -1],
               [-1, -1, 0, -1, -1, 0, -1, 0],
               [-1, -1, -1, 100, -1, -1, 0, -1]
              ])

Maze Structure 2                    
 _____________________________________
|       |          |          |       |
|   0*       1          2     |   3   |
|       |          |          |       |
|__   __|__________|___   ____|__   __|
|       |          |          |       |
|   4   |     5         6     |   7   |
|       |          |                  |
|_______|____  ____|____  ____|__  ___|
        |          |          |       |
        |          |     10   |   8   |
        |                     |       |
        |    11    |__________|__   __|
        |   ++++   |          |  +++  |                              
        |          |          |   9   |
        |__________|          |_______|
#               0   1   2   3   4   5   6   7   8   9   10  11  
R = np.matrix([[-1, 0, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1],
               [0, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1],
               [-1, 0, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1],
               [-1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1],
               [0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
               [-1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 100],
               [-1, -1, 0, -1, -1,  0, -1,  0, -1, -1,  0, -1],
               [-1, -1, -1, 0, -1, -1,  0, -1,  0, -1, -1, -1],
               [-1, -1, -1, -1, -1, -1, -1, 0, -1,100, -1, -1],
               [-1, -1, -1, -1, -1, -1, -1, -1, -1,100, -1, -1],
               [-1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 100],
               [-1, -1, -1, -1, -1, 0, -1, -1, -1, -1, -1, 100]
              ])

*    --> Start
+++  --> Target

"""


'\n\nMaze structure 1\n                                   ___\n _________________________________|+++|\n|       |          |          |       |\n|   0*  |    1          2     |   3   |\n|       |          |          |       |\n|__   __|____   ___|___   ____|__   __|\n|       |          |          |       |\n|   4   |     5    |    6     |   7   |\n|                                     |\n|_______|__________|__________|_______|\n\nR = np.matrix([[-1, -1, -1, -1, 0, -1, -1, -1],\n               [-1, -1, 0, -1, -1, 0, -1, -1],\n               [-1, 0, -1, -1, -1, -1, 0, -1],\n               [-1, -1, -1, 100, -1, -1, -1, 0],\n               [0, -1, -1, -1, -1, 0, -1, -1],\n               [-1, 0, -1, -1, 0, -1, 0, -1],\n               [-1, -1, 0, -1, -1, 0, -1, 0],\n               [-1, -1, -1, 100, -1, -1, 0, -1]\n              ])\n\nMaze Structure 2                    \n _____________________________________\n|       |          |          |       |\n|   0*       1          2     |   3   |\n

In [5]:
R = np.matrix([[-1, 0, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1],
               [0, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1],
               [-1, 0, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1],
               [-1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1],
               [0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
               [-1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 100],
               [-1, -1, 0, -1, -1,  0, -1,  0, -1, -1,  0, -1],
               [-1, -1, -1, 0, -1, -1,  0, -1,  0, -1, -1, -1],
               [-1, -1, -1, -1, -1, -1, -1, 0, -1,100, -1, -1],
               [-1, -1, -1, -1, -1, -1, -1, -1, -1,100, -1, -1],
               [-1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 100],
               [-1, -1, -1, -1, -1, 0, -1, -1, -1, -1, -1, 100]
              ])



Q = np.zeros(R.shape)

gamma = 0.8

initial_state = 0

Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:

def available_actions(state):
    return np.where(R[state] >= 0)[1]
for i in range(8):
    print(i, available_actions(i))

0 [1 4]
1 [0 2]
2 [1 6]
3 [7]
4 [0]
5 [ 6 11]
6 [ 2  5  7 10]
7 [3 6 8]


In [7]:
def updateQ(current_state, action, gamma):
    max_index = np.where(Q[action] == np.max(Q[action]))[0]
    
    if(max_index.shape[0] > 1):
        max_index = np.random.choice(max_index, size = 1)
    max_index = int(max_index)

    max_val = Q[action, max_index]
    Q[current_state, action] = R[current_state, action] + gamma * max_val
    
updateQ(initial_state, available_actions(initial_state), gamma)
Q


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
Q = np.zeros(R.shape)
for i in range(10000):
    current_state = np.random.randint(0, Q.shape[0])
    actions = available_actions(current_state)
    
    next_action = int(np.random.choice(actions, 1))
    updateQ(current_state, next_action, gamma)
    current_state = next_action
Q = Q / np.max(Q)
Q, R


(array([[0.      , 0.4096  , 0.      , 0.      , 0.262144, 0.      ,
         0.      , 0.      , 0.      , 0.      , 0.      , 0.      ],
        [0.32768 , 0.      , 0.512   , 0.      , 0.      , 0.      ,
         0.      , 0.      , 0.      , 0.      , 0.      , 0.      ],
        [0.      , 0.4096  , 0.      , 0.      , 0.      , 0.      ,
         0.64    , 0.      , 0.      , 0.      , 0.      , 0.      ],
        [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
         0.      , 0.64    , 0.      , 0.      , 0.      , 0.      ],
        [0.32768 , 0.      , 0.      , 0.      , 0.      , 0.      ,
         0.      , 0.      , 0.      , 0.      , 0.      , 0.      ],
        [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
         0.64    , 0.      , 0.      , 0.      , 0.      , 1.      ],
        [0.      , 0.      , 0.512   , 0.      , 0.      , 0.8     ,
         0.      , 0.64    , 0.      , 0.      , 0.8     , 0.      ],
        [0.      , 0.      

In [9]:

current_state = 0
while current_state != 11:
    next_step = np.where(Q[current_state, ] == np.max(Q[current_state, ]))[0]
    if(next_step.shape[0] > 1):
        next_step = np.random.choice(next_step, size = 1)
    next_step = int(next_step)

    print(current_state, "->", end=" ")
    current_state = next_step
print(current_state)

0 -> 1 -> 2 -> 6 -> 10 -> 11
